# codemagic.yaml
# ملف تكوين Codemagic.io لمشروع Flutter
#
# ملاحظة هامة: يجب على المستخدم رفع ملف التوقيع (Keystore) إلى Codemagic
# وتعيين متغيرات البيئة التالية في إعدادات التطبيق على Codemagic:
# CM_KEYSTORE_PASSWORD
# CM_KEY_ALIAS
# CM_KEY_PASSWORD

workflows:
  android-release-build:
    name: Android Release APK Build
    # استخدام جهاز Mac Mini M1 لضمان أداء جيد وسرعة في البناء
    instance_type: mac_mini_m1
    
    environment:
      # تحديد إصدار Flutter
      flutter: stable
      # تحديد إصدار Xcode (مطلوب حتى لو كان البناء لـ Android فقط)
      xcode: latest
      cocoapods: default
      # تعريف متغيرات البيئة الخاصة بالتوقيع (سيتم سحبها من إعدادات Codemagic)
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
        CM_KEYSTORE_ID: [Your Keystore ID in Codemagic]
        CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        CM_KEY_ALIAS: $CM_KEY_ALIAS
        CM_KEY_PASSWORD: $CM_KEY_PASSWORD
    
    scripts:
      - name: Set up Flutter
        script: |
          # التحقق من إعدادات Flutter
          flutter doctor
      
      - name: Get Flutter dependencies
        script: |
          # جلب التبعيات
          flutter pub get
          
      - name: Build Android Release APK
        script: |
          # بناء ملف APK في وضع الإطلاق (Release)
          # سيتم استخدام متغيرات البيئة الخاصة بالتوقيع تلقائيًا
          flutter build apk --release
          
    artifacts:
      # تحديد مسار ملف APK الناتج ليتم حفظه كـ "artifact"
      - build/app/outputs/flutter-apk/app-release.apk
      
    publishing:
      # يمكن إضافة خطوات النشر هنا (مثل Google Play)
      # في الوقت الحالي، نكتفي بحفظ ملف APK
      
    triggering:
      # إعدادات التشغيل التلقائي (اختياري)
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
        - pattern: main
          include: true
        - pattern: develop
          include: true
